import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./../styles/main.scss";

const imb = IBM_Plex_Sans({
  variable: "--font-ibm",
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Al Amin Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={imb.className}>{children}</body>
    </html>
  );
}
